package TP2;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.util.Random;

public class MainWindow {
    private JButton spawnPigeonBtn;
    private JPanel drawPanel;
    private JPanel mainPanel;
    private World world;

    public MainWindow(World world) {
        this.world = world;
        $$$setupUI$$$();
        drawPanel.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                world.spawnFood(e.getPoint());
            }
        });
        spawnPigeonBtn.addActionListener(actionEvent -> {
            world.spawnPigeon(world.randomPos());
        });
        drawPanel.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                world.setDim(drawPanel.getSize());
            }
        });
    }

    JPanel getSwingPanel() {
        return mainPanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(drawPanel, gbc);
        spawnPigeonBtn = new JButton();
        spawnPigeonBtn.setText("Spawn Pigeon");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        mainPanel.add(spawnPigeonBtn, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

    private void createUIComponents() {
        drawPanel = new DrawPanel(world);
    }
}
